[package]
name = "brev"
version = "0.1.8"
authors = ["Casey Rodarmor <casey@rodarmor.com>"]
description = "helpers for quick and dirty scripting"
license = "WTFPL"
repository = "https://github.com/casey/brev"

[dependencies]

glob = "0.2.11"
tempdir = "0.3"
